// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class ClienteXcuenta
{
    public int Id { get; set; }

    public DateOnly Alta { get; set; }

    public int IdCliente { get; set; }

    public int IdCuenta { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Cuenta IdCuentaNavigation { get; set; }
}