// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Sucursal
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Calle { get; set; }

    public string Departamento { get; set; }

    public string Numero { get; set; }

    public int? IdLocalidad { get; set; }

    public virtual ICollection<Cuenta> Cuenta { get; set; } = new List<Cuenta>();

    public virtual ICollection<Empleado> Empleado { get; set; } = new List<Empleado>();

    public virtual Localidad Localidad { get; set; }
}