// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Transaccion
{
    public int Id { get; set; }

    public float Monto { get; set; }

    public long Numero { get; set; }

    public DateTime Acreditacion { get; set; }

    public DateTime Realizacion { get; set; }

    public string Motivo { get; set; }

    public string Referencia { get; set; }

    public int IdCuentaOrigen { get; set; }

    public int IdCuentaDestino { get; set; }

    public int IdTipoTransaccion { get; set; }

    [JsonIgnore]
    public virtual Cuenta CuentaDestino { get; set; }
    [JsonIgnore]
    public virtual Cuenta CuentaOrigen { get; set; }
    [JsonIgnore]
    public virtual TipoTransaccion TipoTransaccion { get; set; }
}